apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agent-documentation-ingress
  namespace: quantnik-wipro-buildai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.quantnik.wipro.com
      secretName: quantnik-platform-dev-ap-south-1-build-ai-v2
  rules:
    - host: app.quantnik.wipro.com
      http:
        paths:
          - path: /documentation(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: agent-documentation-service
                port:
                  number: 80
