# config/aws/dev.yaml
# AWS ECS - Development

env:
  ENVIRONMENT: dev
  LOG_LEVEL: DEBUG
  FEATURE_DEBUG_MODE: "true"
  FEATURE_VERBOSE_ERRORS: "true"
  
  API_BASE_URL: https://dev-api.quantnik.aws.example.com
  
  DB_HOST: dev-quantnik-db.xxxxx.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: quantnik_dev
  
  MAX_WORKERS: "2"
