import uuid
from datetime import UTC, datetime

from sqlalchemy import Column, DateTime, Integer, JSON, String, Text
from sqlalchemy.dialects.postgresql import UUID

from app.db.base import Base


class Conversation(Base):
    __tablename__ = "conversations"

    id               = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    conversation_id  = Column(String(255), nullable=False, unique=True, index=True)
    project_name     = Column(String(255), nullable=False, index=True)
    # JSON list of {role, content, timestamp}
    turns            = Column(JSON, nullable=False, default=list)
    # Compressed summary of older turns (generated by LLM after N turns)
    summary          = Column(Text, nullable=True)
    turn_count       = Column(Integer, default=0)
    created_at       = Column(DateTime, default=lambda: datetime.now(UTC))
    updated_at       = Column(DateTime, default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC))
