# config/azure/dev.yaml
# Azure Container Apps - Development

env:
  ENVIRONMENT: dev
  LOG_LEVEL: DEBUG
  FEATURE_DEBUG_MODE: "true"
  FEATURE_VERBOSE_ERRORS: "true"
  
  API_BASE_URL: https://dev-api.wega.azurecontainer.io
  
  DB_HOST: dev-wega-db.postgres.database.azure.com
  DB_PORT: "5432"
  DB_NAME: wega_dev
  
  MAX_WORKERS: "2"
